language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake metrics:coverage"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-19mode
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
notifications:
  email:
    - piotr.solnica@gmail.com
